spring.application.name=crud.employee

spring.datasource.url=jdbc:mysql://localhost:3306/emp_crud
spring.datasource.username=root
spring.datasource.password=Likhitha@823
spring.jpa.hibernate.ddl-auto=update
server.port=8082

